DROP TABLE IF EXISTS post_images;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS store_aliases;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS venues;
DROP TABLE IF EXISTS campuses;
